### ISSUE TITLE
Doc Feedback: Reference link not working in hybrid gateway page

### ISSUE THREAD

**Issue by erandiganepola** [wso2/docs-cloud#65]
Location : https://cloud.docs.wso2.com/en/latest/hybrid-api-management/overview/

"here" option in following section directs me to a "Page not found":
_Now that you understand the basics of hybrid API management and its benefits, let's try out the Microgateway of WSO2 API Cloud. Click **here** for instructions on how you can quickly download, configure, and run the Microgateway._

**Comment by Nashaath** [comment]
Fixed via https://github.com/wso2/docs-cloud/pull/67

**Comment by Nashaath** [comment]
The link is working as expected now.
